version: '2'
services:
  db:
    image: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=DTj4OatAgs0PX33mx7Pz
      - MYSQL_DATABASE=jishi
      - MYSQL_USER=jishi
      - MYSQL_PASSWORD=5bZnNBnlo69xTirkGQjb

  vault-dev:
    image: vault
    expose:
      - 8200
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK