spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
  jpa:
      show-sql: true
      database: mysql
      hibernate:
          ddl-auto: validate
          use-new-id-generator-mappings: false
  data:
    rest:
      base-path: /api
  datasource:
      url: @db.url@
      username: @db.user@
      password: @db.pass@
      driver-class-name: com.mysql.jdbc.Driver

springfox:
  documentation:
    swagger:
      v2:
        path: /api